dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: lva-document-handler
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.7.14
- name: lva-electronic-page-handler
  repository: http://jenkins-x-chartmuseum:8080
  version: 2.3.10
- name: lva-electronic-page-processor
  repository: http://jenkins-x-chartmuseum:8080
  version: 2.2.5
- name: lva-slip-generator
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.4.3
- name: lva-spreadsheet-generator
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.3.3
- name: lva-wingman-templates
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.3.9
- name: lva-wingman-ui
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.3.8
