dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: lva-slip-generator
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.4.3
- name: lva-spreadsheet-generator
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.3.3
