dependencies:
- name: exposecontroller
  version: 2.3.89
  repository: https://chartmuseum.jx.wingman.lvalogic.com
  alias: expose
- name: exposecontroller
  version: 2.3.89
  repository: https://chartmuseum.jx.wingman.lvalogic.com
  alias: cleanup
