dependencies:
- name: exposecontroller
  version: 2.3.89
  repository: http://jenkins-x-chartmuseum:8080
  alias: expose
- name: exposecontroller
  version: 2.3.89
  repository: http://jenkins-x-chartmuseum:8080	
  alias: cleanup
